databases:
  - name: meu_db
    plan: free
    databaseName: meu_projeto
    user: meu_usuario

services:
  - type: web
    plan: free
    name: app-agenda
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn project.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: meu_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "4"
